baseURL = "http://www.nnavi.eu"
languageCode = "en-us"
title = "My language diaries"
theme = "hugo-theme-nnavi"
[params]
author = "Nnavi"
description = "На мама и татко. Обичам ви!"
avatar = "avatar.jpg"
[permalinks]
  spanish = "/:section/"
  italian = "/:section/"
  portuguese = "/:section/"
 [[params.social]]

    name = "github"

    url = "https://github.com/nnnavi"

 

 #[params.style]
 # darkestColor = "#d35050"
#  darkColor = "#212121"
 # lightColor = "#f5e3e0"
  #lightestColor = "#f5f5f5"
 # primaryColor = "#fff"