baseURL = "http://www.nnavi.eu"
languageCode = "en-us"
title = "My language diaries"
theme = "hugo-theme-m10c"
[params]
author = "Nnavi"
description = "Spanish Italian Portuguese"
avatar = "avatar.jpg"

 [[params.social]]

    name = "github"

    url = "https://github.com/nnnavi"

 

 #[params.style]
 # darkestColor = "#d35050"
#  darkColor = "#212121"
 # lightColor = "#f5e3e0"
  #lightestColor = "#f5f5f5"
 # primaryColor = "#fff"